<a href="https://colab.research.google.com/github/MahekLasi028/DSBDAL/blob/main/Prac3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Descriptive Statistics - Measures of Central Tendency and variability
Perform the following operations on any open source dataset (e.g., data.csv)
1.	Provide summary statistics (mean, median, minimum, maximum, standard deviation) for a dataset (age, income etc.) with numeric variables grouped by one of the qualitative (categorical) variable. For example, if your categorical variable is age groups and quantitative variable is income, then provide summary statistics of income grouped by the age groups. Create a list that contains a numeric value for each response to the categorical variable.  
2.	Write a Python program to display some basic statistical details like percentile, mean,
standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’ of iris.csv dataset.

 Provide the codes with outputs and explain everything that you do in this step.

In [19]:
import pandas as pd

In [20]:
df=pd.read_csv("/content/iris.data")

In [21]:
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [22]:
df.describe()

              5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [23]:
df['Iris-setosa'].describe()

count                 149
unique                  3
top       Iris-versicolor
freq                   50
Name: Iris-setosa, dtype: object

In [24]:
df.groupby("0.2").describe().sum()

5.1  count    149.000000
     mean     130.423200
     std       10.124326
     min      119.200000
     25%      124.575000
     50%      129.750000
     75%      134.975000
     max      144.100000
3.5  count    149.000000
     mean      66.895387
     std        5.682537
     min       59.500000
     25%       64.350000
     50%       66.950000
     75%       69.200000
     max       74.600000
1.4  count    149.000000
     mean      88.930772
     std        7.605937
     min       80.500000
     25%       84.600000
     50%       87.800000
     75%       92.375000
     max      100.100000
dtype: float64